Algoritmo "semnome"

Var
// Seção de Declarações das variáveis 
      N1, N2, S: Inteiro
      nome: caractere

Inicio
     ESCREVA ("Digite seu nome: ")
      Leia (nome)
     Escreva ("Olá ", nome)
     Escreval (", Este é um servicço de soma de dois números!")
     Escreva ("Informe um número: ")
       Leia (N1)
     Escreva ("Informe outro número: ")
       Leia (N2)
         S <- N1 + N2
     Escreva ("Seu resultado é: ", S )
Fimalgoritmo